package polyakov.nametranscriptor.model.rulesets;

public enum RussianNames {
    ADEL("Adel", "Адель"),
    AIDA("Aida", "Аида"),
    AFANASI("Afanasi", "Афанасий"),
    AFANASIY("Afanasiy", "Афанасий"),
    AFANASY("Afanasy", "Афанасий"),
    AGNIIA("Agniia", "Агния"),
    ALBERT("Albert", "Альберт"),
    ALBINA("Albina", "Альбина"),
    ALEXANDER("Alexander", "Александр"),
    ALEXANDRE("Alexandre", "Александр"),
    ALIONA("Aliona", "Алена"),
    ALYONA("Alyona", "Алена"),
    AMALIIA("Amaliia", "Амалия"),
    ANATOLI("Anatoli", "Анатолий"),
    ANATOLIY("Anatoliy", "Анатолий"),
    ANATOLY("Anatoly", "Анатолий"),
    ARKADI("Arkadi", "Аркадий"),
    ARKADIY("Arkadiy", "Аркадий"),
    ARKADY("Arkady", "Аркадий"),
    ARSENI("Arseni", "Арсений"),
    ARSENIY("Arseniy", "Арсений"),
    ARSENY("Arseny", "Арсений"),
    ARTEMI("Artemi", "Артемий"),
    ARTEMIY("Artemiy", "Артемий"),
    ARTEMY("Artemy", "Артемий"),
    ARTIOM("Artiom" , "Артем"),
    ARTYOM("Artyom" , "Артем"),
    AVDOTIA("Avdotia", "Авдотья"),
    AVDOTYA("Avdotya", "Авдотья"),
    AZALIIA("Azaliia", "Азалия"),
    DARIA("Daria", "Дарья"),
    DARYA("Darya", "Дарья"),
    DEMYAN("Demyan", "Демьян"),
    DEMIAN("Demian", "Демьян"),
    DMITRI("Dmitri", "Дмитрий"),
    DMITRY("Dmitry", "Дмитрий"),
    EFIM("Efim", "Ефим"),
    EGOR("Egor", "Егор"),
    EKATRINA("Ekaterina", "Екатерина"),
    ELENA("Elena", "Елена"),
    ELEONORA("Eleonora", "Элеонора"),
    ELINA("Elina", "Элина"),
    ELISEI("Elisei", "Елисей"),
    ELIZAVETA("Elizaveta", "Елизавета"),
    ELMIRA("Elmira", "Эльмира"),
    ELVIRA("Elvira", "Эльвира"),
    ELZA("Elza", "Эльза"),
    EMIL("Emil", "Эмиль"),
    EMILIIA("Emiliia", "Эмилия"),
    ESENIYA("Eseniya", "Есения"),
    EVA("Eva", "Ева"),
    EVANGELINA("Evangelina", "Евангелина"),
    EVDOKIYA("Evdokiya", "Евдокия"),
    EVELINA("Evelina", "Эвелина"),
    EVGENI("Evgeni", "Евгений"),
    EVGENII("Evgenii", "Евгений"),
    EVGENIY("Evgeniy", "Евгений"),
    EVGENIYA("Evgeniya", "Евгения"),
    EVGENY("Evgeny", "Евгений"),
    FIODOR("Fiodor", "Федор"),
    FYODOR("Fyodor", "Федор"),
    GENNADI("Gennadi", "Геннадий"),
    GENNADIY("Gennadiy", "Геннадий"),
    GENNADY("Gennady", "Геннадий"),
    GEORGI("Georgi", "Георгий"),
    GEORGIY("Georgiy", "Георгий"),
    GEORGY("Georgy", "Георгий"),
    GRIGORI("Grigori", "Григорий"),
    GRIGORY("Grigory", "Григорий"),
    IGOR("Igor", "Игорь"),
    ILIA("Ilia", "Илья"),
    ILYA("Ilya", "Илья"),
    IOURI("Iouri", "Юрий"),
    IOURII("Iourii", "Юрий"),
    IOURY("Ioury", "Юрий"),
    IRAKLI("Irakli", "Ираклий"),
    IRAKLIY("Irakliy", "Ираклий"),
    IRAKLY("Irakly", "Ираклий"),
    IULIIA("Iuliia", "Юлия"),
    IULIA("Iulia", "Юлия"),
    IULIYA("Iuliya", "Юлия"),
    IULIANA("Iuliana", "Юлиана"),
    JULIA("Iulia", "Юлия"),
    JULIIA("Juliia", "Юлия"),
    JULIANA("Iuliana", "Юлиана"),
    LAVRENTI("Lavrenti", "Лаврентий"),
    LAVRENTY("Lavrenty", "Лаврентий"),
    LIIA("Liia", "Лия"),
    LILIIA("Liliia", "Лилия"),
    LIDIIA("Lidiia", "Лидия"),
    LIUBOV("Liubov", "Любовь"),
    LYUBOV("Lyubov", "Любовь"),
    LUBOV("Lubov", "Любовь"),
    LIUDMILA("Liudmila", "Людмила"),
    LUDMILA("Ludmila", "Людмила"),
    MARIA("Maria", "Мария"),
    MARIIA("Mariia", "Мария"),
    MARYA("Marya", "Марья"),
    MELANIIA("Melaniia", "Мелания"),
    NASTASYA("Nastasya", "Настасья"),
    NATALIIA("Nataliia", "Наталия"),
    NATALYA("Natalya", "Наталья"),
    OLGA("Olga", "Ольга"),
    OLIVIIA("Oliviia", "Оливия"),
    SAVELI("Saveli", "Савелий"),
    SAVELIY("Saveliy", "Савелий"),
    SAVELY("Savely", "Савелий"),
    SEMION("Semion", "Семен"),
    SEMYON("Semyon", "Семен"),
    SILVIIA("Silviia", "Сильвия"),
    SILVIYA("Silviya", "Сильвия"),
    SOFIIA("Sofiia", "София"),
    SOFYA("Sofya", "Софья"),
    STEFANIIA("Stefaniia", "Стефания"),
    STEFANIYA("Stefaniya", "Стефания"),
    VALERIIA("Valeriia", "Валерия"),
    ULYAN("Ulyan", "Ульян"),
    ULYANA("Ulyana", "Ульяна"),
    VALERIA("Valeria", "Валерия"),
    VASILI("Vasili", "Василий"),
    VASILIY("Vasiliy", "Василий"),
    VASILY("Vasily", "Василий"),
    VIKTORIIA("Viktoriia", "Виктория"),
    VITALI("Vitali", "Виталий"),
    VITALIY("Vitaliy", "Виталий"),
    VITALY("Vitaly", "Виталий"),
    YEFIM("Yefim", "Ефим"),
    YULI("Yuli", "Юлий"),
    YULIIA("Yuliia", "Юлия"),
    YULIA("Yulia", "Юлия"),
    YULIY("Yuliy", "Юлий"),
    YULY("Yuly", "Юлий"),
    YURI("Yuri", "Юрий"),
    YURY("Yury", "Юрий");

    private final String latinName;
    private final String cyrillicName;

    RussianNames(String latinName, String cyrillicName) {
        this.latinName = latinName;
        this.cyrillicName = cyrillicName;
    }

    public String getLatinName() {
        return latinName;
    }

    public String getCyrillicName() {
        return cyrillicName;
    }
}