package polyakov.nametranscriptor.ruleset.resources.popularnames;

public enum RussianNames {
    ADEL("adel", "адель"),
    ADIL("adil", "адиль"),
    AIDA("aida", "аида"),
    AFANASI("afanasi", "Афанасий"),
    AFANASY("afanasy", "афанасий"),
    ALBERT("albert", "альберт"),
    ALBINA("albina", "альбина"),
    ALEKSANDER("aleksander", "александр"),
    ALEKSANDAR("aleksandar", "александр"),
    ALEXANDER("alexander", "александр"),
    ALEXANDAR("alexandar", "александр"),
    ALEXANDRE("alexandre", "александр"),
    ALIONA("aliona", "алена"),
    ALYONA("alyona", "алена"),
    ANATOLI("anatoli", "анатолий"),
    ANATOLIY("anatoliy", "анатолий"),
    ANATOLY("anatoly", "анатолий"),
    ARKADI("arkadi", "аркадий"),
    ARKADIY("arkadiy", "аркадий"),
    ARKADY("arkady", "аркадий"),
    ARSENI("arseni", "арсений"),
    ARSENIY("arseniy", "арсений"),
    ARSENY("arseny", "арсений"),
    ARTEMI("artemi", "артемий"),
    ARTEMIY("artemiy", "артемий"),
    ARTEMY("artemy", "артемий"),
    ARTIOM("artiom", "артем"),
    ARTYOM("artyom", "артем"),
    AVDOTIA("avdotia", "авдотья"),
    AVDOTYA("avdotya", "авдотья"),
    DARIA("daria", "дарья"),
    DARYA("darya", "дарья"),
    DEMYAN("demyan", "демьян"),
    DEMIAN("demian", "демьян"),
    DMITRI("dmitri", "дмитрий"),
    DMITRY("dmitry", "дмитрий"),
    EFIM("efim", "ефим"),
    EGOR("egor", "егор"),
    EKATERINA("ekaterina", "екатерина"),
    ELENA("elena", "елена"),
    ELEONORA("eleonora", "элеонора"),
    ELINA("elina", "элина"),
    ELISEI("elisei", "елисей"),
    ELIZAVETA("elizaveta", "елизавета"),
    ELMIRA("elmira", "эльмира"),
    ELVIRA("elvira", "эльвира"),
    ELZA("elza", "эльза"),
    EMMANUIL("emmanuil", "эммануил"),
    EMIL("emil", "эмиль"),
    ESENIA("esenia", "есения"),
    ESENIIA("eseniia", "есения"),
    ESENIYA("eseniya", "есения"),
    EVA("eva", "ева"),
    EVANGELINA("evangelina", "евангелина"),
    EVDOKIYA("evdokiya", "евдокия"),
    EVELINA("evelina", "эвелина"),
    EVGENI("evgeni", "евгений"),
    EVGENIY("evgeniy", "евгений"),
    EVGENIA("evgenia", "евгения"),
    EVGENIIA("evgeniia", "евгения"),
    EVGENIYA("evgeniya", "евгения"),
    EVGENY("evgeny", "евгений"),
    FAIL("fail", "фаиль"),
    FIODOR("fiodor", "федор"),
    FYODOR("fyodor", "федор"),
    GENNADI("gennadi", "геннадий"),
    GENNADIY("gennadiy", "геннадий"),
    GENNADY("gennady", "геннадий"),
    GEORGI("georgi", "георгий"),
    GEORGY("georgy", "георгий"),
    GRIGORI("grigori", "григорий"),
    GRIGORY("grigory", "григорий"),
    IGOR("igor", "игорь"),
    ILIA("ilia", "илья"),
    ILYA("ilya", "илья"),
    IOURI("iouri", "юрий"),
    IOURII("iourii", "юрий"),
    IOURY("ioury", "юрий"),
    IURI("iuri", "юрий"),
    IURII("iurii", "юрий"),
    IURY("iury", "юрий"),
    IRAKLI("irakli", "ираклий"),
    IRAKLIY("irakliy", "ираклий"),
    IRAKLY("irakly", "ираклий"),
    JULIANA("juliana", "юлиана"),
    KAMIL("kamil", "камиль"),
    LAVRENTI("lavrenti", "лаврентий"),
    LAVRENTY("lavrenty", "лаврентий"),
    LIUBOV("liubov", "любовь"),
    LYUBOV("lyubov", "любовь"),
    LUBOV("lubov", "любовь"),
    LUKIAN("lukian", "лукьян"),
    LIUDMILA("liudmila", "людмила"),
    LUDMILA("ludmila", "людмила"),
    LIUBOMIR("liubomir", "любомир"),
    MARYA("marya", "марья"),
    MARYANA("maryana", "марьяна"),
    MICHAIL("michail", "михаил"),
    NAIL("nail", "наиль"),
    NASTASYA("nastasya", "настасья"),
    NATALIIA("nataliia", "наталия"),
    NATALYA("natalya", "наталья"),
    NIKOLAI("nikolai", "николай"),
    OLGA("olga", "ольга"),
    RAIL("rail", "раиль"),
    RAMIL("ramil", "рамиль"),
    SAVELI("saveli", "савелий"),
    SAVELIY("saveliy", "савелий"),
    SAVELY("savely", "савелий"),
    SEMION("semion", "семен"),
    SEMYON("semyon", "семен"),
    SHAMIL("shamil", "шамиль"),
    SILVIIA("silviia", "сильвия"),
    SILVIYA("silviya", "сильвия"),
    SILVIA("silvia", "сильвия"),
    SILVYA("silvya", "сильвия"),
    SOFYA("sofya", "софья"),
    SVIATOPOLK("sviatopolk", "святополк"),
    SVIATOSLAV("sviatoslav", "святослав"),
    TATIANA("tatiana", "татьяна"),
    TATYANA("tatyana", "татьяна"),
    ULIAN("ulian", "ульян"),
    ULYAN("ulyan", "ульян"),
    ULIANA("uliana", "ульяна"),
    ULYANA("ulyana", "ульяна"),
    VALERI("valeri", "валерий"),
    VASILI("vasili", "василий"),
    VASILIY("vasiliy", "василий"),
    VASILY("vasily", "василий"),
    VIACHESLAV("viacheslav", "вячеслав"),
    VICTOR("viktor", "виктор"),
    VICTORIA("victoria", "виктория"),
    VICTORIIA("victoriia", "виктория"),
    VICTORIYA("victoriya", "виктория"),
    VITALI("vitali", "виталий"),
    VITALIY("vitaliy", "виталий"),
    VITALY("vitaly", "виталий"),
    YEFIM("yefim", "ефим"),
    YULI("yuli", "юлий"),
    YULIY("yuliy", "юлий"),
    YULY("yuly", "юлий"),
    YURI("yuri", "юрий"),
    YURY("yury", "юрий");

    private final String latinName;
    private final String cyrillicName;

    RussianNames(String latinName, String cyrillicName) {
        this.latinName = latinName;
        this.cyrillicName = cyrillicName;
    }

    public String getLatinName() {
        return latinName;
    }

    public String getCyrillicName() {
        return cyrillicName;
    }
}