package polyakov.nametranscriptor.model.rulesets.names;

public enum RussianNames {
    ADEL("adel", "адель"),
    AIDA("aida", "аида"),
    AFANASI("afanasi", "Афанасий"),
    AFANASIY("afanasiy", "афанасий"),
    AFANASY("afanasy", "афанасий"),
    AGNIIA("agniia", "агния"),
    ALBERT("albert", "альберт"),
    ALBINA("albina", "альбина"),
    ALEKSANDER("aleksander", "александр"),
    ALEKSANDAR("aleksandar", "александр"),
    ALEXANDER("alexander", "александр"),
    ALEXANDAR("alexandar", "александр"),
    ALEXANDRE("alexandre", "александр"),
    ALIONA("aliona", "алена"),
    ALYONA("alyona", "алена"),
    AMALIIA("amaliia", "амалия"),
    ANATOLI("anatoli", "анатолий"),
    ANATOLIY("anatoliy", "анатолий"),
    ANATOLY("anatoly", "анатолий"),
    ARKADI("arkadi", "аркадий"),
    ARKADIY("arkadiy", "аркадий"),
    ARKADY("arkady", "аркадий"),
    ARSENI("arseni", "арсений"),
    ARSENIY("arseniy", "арсений"),
    ARSENY("arseny", "арсений"),
    ARTEMI("artemi", "артемий"),
    ARTEMIY("artemiy", "артемий"),
    ARTEMY("artemy", "артемий"),
    ARTIOM("artiom", "артем"),
    ARTYOM("artyom", "артем"),
    AVDOTIA("avdotia", "авдотья"),
    AVDOTYA("avdotya", "авдотья"),
    AZALIIA("azaliia", "азалия"),
    DARIA("daria", "дарья"),
    DARYA("darya", "дарья"),
    DEMYAN("demyan", "демьян"),
    DEMIAN("demian", "демьян"),
    DMITRI("dmitri", "дмитрий"),
    DMITRIY("dmitry", "дмитрий"),
    DMITRY("dmitry", "дмитрий"),
    EFIM("efim", "ефим"),
    EGOR("egor", "егор"),
    EKATRINA("ekaterina", "екатерина"),
    ELENA("elena", "елена"),
    ELEONORA("eleonora", "элеонора"),
    ELINA("elina", "элина"),
    ELISEI("elisei", "елисей"),
    ELIZAVETA("elizaveta", "елизавета"),
    ELMIRA("elmira", "эльмира"),
    ELVIRA("elvira", "эльвира"),
    ELZA("elza", "эльза"),
    EMIL("emil", "эмиль"),
    EMILIIA("emiliia", "эмилия"),
    ESENIYA("eseniya", "есения"),
    EVA("eva", "ева"),
    EVANGELINA("evangelina", "евангелина"),
    EVDOKIYA("evdokiya", "евдокия"),
    EVELINA("evelina", "эвелина"),
    EVGENI("evgeni", "евгений"),
    EVGENII("evgenii", "евгений"),
    EVGENIY("evgeniy", "евгений"),
    EVGENIYA("evgeniya", "евгения"),
    EVGENY("evgeny", "евгений"),
    FIODOR("fiodor", "федор"),
    FYODOR("fyodor", "федор"),
    GENNADI("gennadi", "геннадий"),
    GENNADIY("gennadiy", "геннадий"),
    GENNADY("gennady", "геннадий"),
    GEORGI("georgi", "георгий"),
    GEORGIY("georgiy", "георгий"),
    GEORGY("georgy", "георгий"),
    GRIGORI("grigori", "григорий"),
    GRIGORY("grigory", "григорий"),
    IGOR("igor", "игорь"),
    ILIA("ilia", "илья"),
    ILYA("ilya", "илья"),
    IOURI("iouri", "юрий"),
    IOURII("iourii", "юрий"),
    IOURY("ioury", "юрий"),
    IRAKLI("irakli", "ираклий"),
    IRAKLIY("irakliy", "ираклий"),
    IRAKLY("irakly", "ираклий"),
    IULIIA("iuliia", "юлия"),
    IULIA("iulia", "юлия"),
    IULIYA("iuliya", "юлия"),
    IULIANA("iuliana", "юлиана"),
    JULIA("iulia", "юлия"),
    JULIIA("juliia", "юлия"),
    JULIANA("juliana", "юлиана"),
    LAVRENTI("lavrenti", "лаврентий"),
    LAVRENTY("lavrenty", "лаврентий"),
    LIIA("liia", "лия"),
    LILIIA("liliia", "лилия"),
    LIDIIA("lidiia", "лидия"),
    LIUBOV("liubov", "любовь"),
    LYUBOV("lyubov", "любовь"),
    LUBOV("lubov", "любовь"),
    LUKIAN("lukian", "лукьян"),
    LIUDMILA("liudmila", "людмила"),
    LUDMILA("ludmila", "людмила"),
    LIUBOMIR("liubomir", "любомир"),
    MARIA("maria", "мария"),
    MARIIA("mariia", "мария"),
    MARYA("marya", "марья"),
    MARYANA("maryana", "марьяна"),
    MICHAIL("michail", "михаил"),
    MELANIIA("melaniia", "мелания"),
    NASTASYA("nastasya", "настасья"),
    NATALIIA("nataliia", "наталия"),
    NATALYA("natalya", "наталья"),
    NIKOLAI("nikolai", "николай"),
    OLGA("olga", "ольга"),
    OLIVIIA("oliviia", "оливия"),
    SAVELI("saveli", "савелий"),
    SAVELIY("saveliy", "савелий"),
    SAVELY("savely", "савелий"),
    SEMION("semion", "семен"),
    SEMYON("semyon", "семен"),
    SILVIIA("silviia", "сильвия"),
    SILVIYA("silviya", "сильвия"),
    SILVIA("silvia", "сильвия"),
    SILVYA("silvya", "сильвия"),
    SOFIIA("sofiia", "софия"),
    SOFYA("sofya", "софья"),
    STEFANIIA("stefaniia", "стефания"),
    STEFANIYA("stefaniya", "стефания"),
    SVIATOPOLK("sviatopolk", "святополк"),
    SVIATOSLAV("sviatoslav", "святослав"),
    VALERIIA("valeriia", "валерия"),
    ULYAN("ulyan", "ульян"),
    ULYANA("ulyana", "ульяна"),
    VALERIA("valeria", "валерия"),
    VASILI("vasili", "василий"),
    VASILIY("vasiliy", "вВасилий"),
    VASILY("vasily", "василий"),
    VIACHESLAV("viacheslav", "вячеслав"),
    VICTOR("viktor", "виктор"),
    VICTORIIA("victoriia", "виктория"),
    VIKTORIA("viktoria", "виктория"),
    VITALI("vitali", "виталий"),
    VITALIY("vitaliy", "виталий"),
    VITALY("vitaly", "виталий"),
    YEFIM("yefim", "ефим"),
    YULI("yuli", "юлий"),
    YULIIA("yuliia", "юлия"),
    YULIA("yulia", "юлия"),
    YULIY("yuliy", "юлий"),
    YULY("yuly", "юлий"),
    YURI("yuri", "юрий"),
    YURY("yury", "юрий");

    private final String latinName;
    private final String cyrillicName;

    RussianNames(String latinName, String cyrillicName) {
        this.latinName = latinName;
        this.cyrillicName = cyrillicName;
    }

    public String getLatinName() {
        return latinName;
    }

    public String getCyrillicName() {
        return cyrillicName;
    }
}